app = "garand"
primary_region = "ord"

[deploy]
  strategy = "bluegreen"
  wait_timeout = "300s"

[vm]
  size = "shared-cpu-1x"
  memory = "256 MB"
  cpu_kind = "shared"

[env]
  NODE_ENV = "production"
  PORT = "3000"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [services.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

  [[services.http_checks]]
  grace_period = "5s"
  interval = "10s"
  method = "GET"
  path = "/"
  protocol = "http"
  restart_limit = 3
  timeout = "2s"
  tls_skip_verify = false

  script_checks = []

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
